### ISSUE TITLE
IconTouch not required

### ISSUE THREAD

**Issue by WhatAKitty** [flasco/Reader_X#3]
https://github.com/flasco/Reader_X/tree/master/src/components/IconTouch

What do think about IconTouch ?
Is it necessary?

I think use Icon and TouchableOpacity directly is enough.

**Comment by flasco** [comment]
It's a personal like，you can use it or achieve it by your self~

**Comment by flasco** [comment]
actually ,  it will be used again in setting page.

**Comment by WhatAKitty** [comment]
The [icon component](https://react-native-training.github.io/react-native-elements/API/icons/) can absolutely replaced it.
[Like what I do in this screen](https://github.com/flasco/Reader_X/blob/master/src/screens/ShelfScreen/index.js#L28)
